server:
  port: ${PORT:8761}
  shutdown: "graceful"
eureka:
  server:
    enable-self-preservation: false
  client:
    register-with-eureka: false
    fetch-registry: false
---
spring:
  config:
    activate:
      on-profile: dev
---