server:
  port: ${PORT:7000}
spring:
  boot:
    admin:
      ui:
        title: Guardian
        brand: Dhaka Power Plant | Guardian
logging:
  level:
    org:
      springframework:
        security: DEBUG
      arun: DEBUG
---
spring:
  config:
    activate:
      on-profile: dev
---